-- UdyogSetu Prototype — PostgreSQL-compatible illustrative schema
-- Synthetic demo records only. No personal identity or government-system data.
CREATE TABLE applicants (id UUID PRIMARY KEY, business_name TEXT NOT NULL, sector TEXT, state TEXT DEFAULT 'Maharashtra', district TEXT, city TEXT, project_size TEXT, investment_crore NUMERIC, employees INTEGER, stage TEXT, hazardous_material BOOLEAN DEFAULT FALSE, compliance_history TEXT, industrial_area TEXT, land_building_info TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE applications (id UUID PRIMARY KEY, application_number TEXT UNIQUE NOT NULL, applicant_id UUID REFERENCES applicants(id), overall_progress INTEGER DEFAULT 0, status TEXT, submitted_at DATE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE departments (id UUID PRIMARY KEY, name TEXT NOT NULL, short_name TEXT, icon TEXT);
CREATE TABLE approval_rules (rule_id TEXT PRIMARY KEY, sector TEXT, state TEXT, district TEXT, project_size TEXT, stage TEXT, approval_name TEXT, approval_type TEXT, authority TEXT, jurisdiction_level TEXT, reason_applicable TEXT, required_documents JSONB, inspection_required BOOLEAN, indicative_sla_days INTEGER, mandatory_manual_review BOOLEAN, risk_category TEXT, source_reference TEXT, last_updated DATE);
CREATE TABLE approval_tasks (id UUID PRIMARY KEY, application_id UUID REFERENCES applications(id), rule_id TEXT REFERENCES approval_rules(rule_id), department_id UUID REFERENCES departments(id), status TEXT, progress INTEGER, assigned_officer TEXT, submission_date DATE, elapsed_days INTEGER, sla_days INTEGER, comments TEXT, action_history JSONB);
CREATE TABLE documents (id UUID PRIMARY KEY, application_id UUID REFERENCES applications(id), name TEXT, document_type TEXT, status TEXT, extracted_fields JSONB, validation JSONB, uploaded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE inspections (id UUID PRIMARY KEY, application_id UUID REFERENCES applications(id), date DATE, time TEXT, location TEXT, department_ids JSONB, status TEXT, type TEXT, notes TEXT);
CREATE TABLE schemes (id UUID PRIMARY KEY, name TEXT, sector TEXT, location TEXT, project_size_min TEXT, project_size_max TEXT, investment_min NUMERIC, investment_max NUMERIC, eligibility_conditions JSONB, description TEXT, official_reference_placeholder TEXT);
CREATE TABLE risk_assessments (id UUID PRIMARY KEY, application_id UUID REFERENCES applications(id), score INTEGER, classification TEXT, factors JSONB, safeguards JSONB, routing_decision TEXT, assessed_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE notifications (id UUID PRIMARY KEY, applicant_id UUID REFERENCES applicants(id), type TEXT, message TEXT, read BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE audit_logs (id UUID PRIMARY KEY, application_id UUID REFERENCES applications(id), actor TEXT, action TEXT, details TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
